### ISSUE TITLE
Error: Cannot find module './../utils/ComposeObjects'

### ISSUE THREAD

**Issue by moda20** [AkashGutha/generator-stencil#1]
Having this error, apparently something is not working in your code, any fix ?
# StackTrace
```
yo stencil
module.js:557
    throw err;
    ^

Error: Cannot find module './../utils/ComposeObjects'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/generator-stencil/app/index.js:6:21)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

# Reproduction Steps: 
```bash
- npm install -g yo
- npm install -g generator-stencil
- yo stencil
```

**Comment by AkashGutha** [comment]
hi, @moda20 please paste the entire error and stack trace and also provide steps of reproduction.

**Comment by moda20** [comment]
@AkashGutha  Done!

**Comment by AkashGutha** [comment]
@moda20 I'm digging into this issue. It works fine locally.

meanwhile if you want to try this generator. you try the following steps:

1. Uninstall Stencil generator `npm uninstall --global generator-stencil`
2. Clone this repo `https://github.com/AkashGutha/generator-stencil.git`
3. cd into the directory
4. link this as a module using `npm link generator-stencil`/`npm link`. this should work.
5. if step 4 fails or has some error try `npm unlink` in the local repo/ try `npm unlink generator-stencil` and repeat. 

now your have setup this tool locally and you can try `yo stencil` in a new terminal

**Comment by AkashGutha** [comment]
@moda20 @Squiggle I've released a new version fixing these issues.

Please confirm, if the issue has been resolved.

**Comment by serdaraglamis** [comment]
@AkashGutha It seems the issue has not been resolved. Same problem

**Comment by AkashGutha** [comment]
@serdaraglamiswhat which version of the tool did you install?

**Comment by serdaraglamis** [comment]
@AkashGutha Here you can find the full stack tree
```
PS D:\Projects\tryout> yo stencil
module.js:471
    throw err;
    ^

Error: Cannot find module '../utils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Users\serda\AppData\Roaming\nvm\v6.11.0\node_modules\generator-stencil\app\index.js:5:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
PS D:\Projects\tryout>

```

**Comment by AkashGutha** [comment]
@serdaraglamis I've made some changes. please, test and let me know

**Comment by AkashGutha** [comment]
@serdaraglamis I've made a new major release.Please,  try the new one and update.

**Comment by Squiggle** [comment]
Confirmed. I'm able to get the generator up and running. Good work! 🎉

I hope to fork and tinker with this at the weekend. Thanks!

**Comment by AkashGutha** [comment]
@squiggle thanks. I'm closing this now.
